# conda env create --file environment.yml
# mamba env create --file environment.yml
name: solubility_model
dependencies:
  - datamol=0.9.2
  - hyperopt=0.2.7
  - ipykernel
  - lightgbm=3.3.5
  - matplotlib=3.7.1
  - molfeat=0.8.6
  - numpy=1.21 # Required for scaffold split float error in chemprop
  - pandas=1.5.3
  - pyprojroot=0.3.0
  - python=3.10
  - rdkit=2022.9.5
  - scikit-learn=1.2.2
  - seaborn=0.12.2
  - shap=0.41.0
  - tqdm=4.65.0
  # Development
  - black
  - ipykernel
  - mypy
  - ruff
  - pip
  - pip:
    - chemprop==1.5.2
    - deepchem==2.7.1
    - dgl==1.1.1
    - dgllife==0.3.2
    - git+https://github.com/bp-kelley/descriptastorus
    - openpyxl==3.1.2
    - pycaret==3.0.2
